### ISSUE TITLE
launchファイルの重複エラーについて

### ISSUE THREAD

**Issue by s-kumada** [choreonoid/choreonoid_ros#22]
## 発生事象
catkin toolsによるビルド後、choreonoid.launchを実行しようとすると下記エラーにより起動できない。
```
RLException: multiple files named [choreonoid.launch] in package [choreonoid_ros]:
- /home/jad/catkin_ws/devel/share/choreonoid_ros/launch/choreonoid.launch
- /home/jad/catkin_ws/src/choreonoid_ros/launch/choreonoid.launch
Please specify full path instead
The traceback for the exception was written to the log file
```
## 発生環境
22.04.4 LTS (Jammy Jellyfish)
[ROS Noetic Ninjemys](http://wiki.ros.org/noetic)
commit 941e09d2568095d6b79c79e5ac0c7d8e53c16634 

## 問題の追跡
エラーメッセージにあるように、devel下とsrc下に同じ名前のlaunchファイルが重複して存在するため、どっちを起動すればよいか不明とのこと。
devel下のlauchについては、CMakeLists.txtの以下の部分
```CMAKE
install(DIRECTORY launch
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
  USE_SOURCE_PERMISSIONS
)
```
によって生成されており、試しに
```CMAKE
install(DIRECTORY 
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
  USE_SOURCE_PERMISSIONS
)
```
とすると再現しなくなる。（devel下にlaunchが生成されない）

## 改善の要望
ROS2は分かりませんが、ROS1向けにはdevel下にlaunchを生成しないように対応頂けますでしょうか。
ご検討宜しくお願い致します。

**Comment by ssr-yuki** [comment]
ご報告ありがとうございます．確かに症状を確認できました．
#16 での提案を受けて導入したlaunchのインストールですが，検証が足りなかったようで申し訳ありません．

既存の要件とこの不具合の解決を両立しようとすると，catkin configにおいて `--install` が設定されているときには catkin_ws/install にインストールし，そうでない場合はインストールをしないという実装が必要になりそうです．対応までいましばらくお待ち下さい．
